url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Kusebauch Nachtschatt
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00B5CA
  secondary: DD92F0  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Marjan Kusebauch
  pic: 1
  position: Graphic Designer
  social:
    - title: tumblr
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: https://instagram.com/kmarjan/

- name: Moritz Nachtschatt
  pic: 2
  position: Photographer and Chief of Business
  social:
    - title: tumblr
      url: http://mnachtschatt.tumblr.com
    - title: facebook
      url: #
    - title: instagram
      url: https://instagram.com/mnachtschatt/
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: 
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty