url: http://www.kn-design.at
#baseurl: /

# Site settings
title: KusebauchNachtschatt
email: office@kn-design.at
description: "KusebauchNachtschatt ist ein Büro für Grafik Design, Fotografie und Werbung, mit Sitz in Wien."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00B5CA
  secondary: E4AD0E  
  secondary-dark: 4D4D4D

# Team names, titles and social links
people:
- name: Marjan Kusebauch
  pic: 1
  position: Art Director
  social:
    - title: facebook
      url: https://www.facebook.com/david.pokorny.925?fref=ts
    - title: instagram
      url: https://instagram.com/kmarjan/

- name: Moritz Nachtschatt
  pic: 2
  position: Fotograf und Chief of Business
  social:
    - title: tumblr
      url: http://mnachtschatt.tumblr.com
    - title: facebook
      url: https://www.facebook.com/mnachtschatt
    - title: instagram
      url: https://instagram.com/mnachtschatt/
      

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Kolingasse 1
  - line: 1090-Wien

# Build settings
markdown: kramdown
permalink: pretty